### ISSUE TITLE
README content

### ISSUE THREAD

**Issue by cleemansen** [movestore/cargo-agent-r#1]
- [ ] what is cargo-agent?
- [ ] step by step instructions introducing a new IO type
    1. fork this repository
    1. add file `src/analyzer/{io_type_label}.R`
    3. add test data input in `tests/testthat/data/{io_type_label}/{io_type_label}.rds`
    4. add test in `tests/testthat/analyzer/{io_type_label}.R`
    5. create PR

**Comment by andreakoelzsch** [comment]
Hi Clemens, I have started with this, but not yet finished, also as I am not sure of all the details. Please complete (also in notes if you like, then I can formulate things out). Thanks
