### ISSUE TITLE
Choose an open source license

### ISSUE THREAD

**Issue by cleemansen** [movestore/cargo-agent-r#4]
https://choosealicense.com/

**Comment by andreakoelzsch** [comment]
I have added the GPL v.3 license to the repsitory as file license.md, hope this is the correct way to do it. If not, please let me know.

**Comment by cleemansen** [comment]
all fine :)

<img width="323" alt="image" src="https://user-images.githubusercontent.com/868171/212896246-e2933a2a-9a47-44c8-8e37-79a6f4abeb8a.png">
